AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Creates an authenticated cloudfront portal
Parameters:
  Alias:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  OriginAccessIdentity:
    Type: String
  OriginDomain:
    Type: String
  WebAuthFunctionRoleArn:
    Type: String
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Alias
        Comment: Authenticated portal
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD", "OPTIONS"]
          Compress: true
          TargetOriginId: secure-website
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        Origins:
          - DomainName: !Ref OriginDomain
            Id: secure-website
            S3OriginConfig:
              OriginAccessIdentity: !Ref OriginAccessIdentity
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
  DomainAlias:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Alias
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false
